author: croxis, kikelkik
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.minecraftcorp.lift.bukkit.LiftPlugin
name: Lift
startup: postworld
version: ${project.version}
description: Simple and easy Lifts and Elevators for Bukkit
softdepend: [NoCheatPlus, NoteBlockAPI]
permissions:
  lift:
    description: Can ride in a lift
    default: true
  lift.change:
    description: Can change lift floors
    default: true
  lift.reload:
    description: Reloads the lift plugin
    default: false
commands:
   lift:
      description: Scans a lift.
      usage: /<command>
      permission: lift
      permission-message: You don't have lift permissions
api-version: 1.16